spring:
  application:
    name: product-catalog-service

  datasource:
    url: jdbc:mysql://localhost:3306/product_catalog?createDatabaseIfNotExist=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  # Add this block to fix the Swagger "Failed to fetch" issue
  server:
    url: http://51.20.184.86:8080
    description: Production EC2 Server

eureka:
  client:
    service-url:
      defaultZone: http://131.163.97.60:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 51.20.184.86