server:
  port: ${PORT:8080}

spring:
  application:
    name: dispatch-transportation-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/dispatch_transportation_service_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Colombo}
    username: ${DB_USERNAME:dispatch_user}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
#  export DB_USERNAME="admin"
#  export DB_PASSWORD="Xiaomi123"
#  export DB_URL="jdbc:mysql://wms-db.cnuco0c4i68g.us-east-2.rds.amazonaws.com:3306/dispatch_transportation_service_db?useSSL=false&allowPublicKeyRetrieval=true"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false



springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

logging:
#  config: classpath:logback-spring.xml
  file:
    path: logs

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://131.163.97.60:8761/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: 13.61.182.157
