server:
  port: 8081

spring:
  application:
    name: supplier-management-service

  datasource:
      url: jdbc:mysql://localhost:3306/supply_service_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Colombo&allowPublicKeyRetrieval=true
      username: supply_user
      password: Sup#12345!
      # username: root
      # password: acpt
      driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

logging:
  level:
    com.wms.supplyservice: DEBUG
    org.hibernate.SQL: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://131.163.97.60:8761/eureka/}
  instance:
    prefer-ip-address: true
    ip-address: 13.61.10.56
    
