version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-inventory_management_db}
      POSTGRES_USER: ${DB_USERNAME:-wms}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-wms}
    volumes:
      - db-data-v2:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    environment:
      DB_URL: "jdbc:postgresql://db:5432/${DB_NAME:-inventory_management_db}"
      DB_USERNAME: ${DB_USERNAME:-wms}
      DB_PASSWORD: ${DB_PASSWORD:-wms}
      SERVER_PORT: ${SERVER_PORT:-8010}
      EUREKA_URL: ${EUREKA_URL:-http://131.163.97.60:8761/eureka/}
      INSTANCE_IP: ${INSTANCE_IP:-35.88.199.189}
    ports:
      - "${SERVER_PORT:-8010}:${SERVER_PORT:-8010}"
    depends_on:
      - db

volumes:
  db-data-v2:
