spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: Storage-Location-Service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: ${DB_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

server:
  port: 8083
  address: 0.0.0.0  # Allows the app to listen on all network interfaces

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# -----------------------------------------------------------------------
# Eureka Client Configuration
# -----------------------------------------------------------------------
eureka:
  client:
    serviceUrl:
      # This points to your Eureka Server on the other Azure VM
      defaultZone: http://131.163.97.60:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    # Forces Eureka to use the Public IP instead of the internal 172.x.x.x address
    prefer-ip-address: true
    ip-address: 20.41.114.181
    
    # Creates a unique ID so Eureka doesn't get confused if you restart the service
    instance-id: ${spring.application.name}:${random.value}
    
    # Optional: Helps Gateway detect if the service goes down faster
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
